version: 2

project_name: ifaceguard

builds:
  - id: ifaceguard
    main: ./cmd/ifaceguard
    binary: ifaceguard
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: ifaceguard
    ids:
      - ifaceguard
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

brews:
  - name: ifaceguard
    ids:
      - ifaceguard
    directory: Formula
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    repository:
      owner: n-r-w
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

release:
  draft: false
